version: '3'

services:

  elasticsearch:
    image: elasticsearch:8.9.1
    container_name: Elasticsearch
    hostname: elasticsearch
    restart: always
    storage_opt:
      size: 1GB
    volumes:
      - ./volumes/elastic-data:/usr/share/elasticsearch/data/
    environment:
      ES_JAVA_OPTS: "-Xmx500m -Xms500m"
      discovery.type: single-node
      ELASTIC_PASSWORD: elastic
      xpack.security.enabled: false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - '9200:9200'
    networks:
      - laborchart
  
  kibana:
    image: kibana:8.9.1
    container_name: Kibana
    restart: always
    storage_opt:
      size: 1GB
    ports:
      - '5601:5601'
    environment:
      ELASTTICSEARCH_URL: http://elasticsearch:9200
      ELASTTICSEARCH_USERNAME: elastic
      ELASTTICSEARCH_PASSWORD: elastic
    depends_on:
      - elasticsearch
    networks:
      - laborchart
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    storage_opt:
      size: 1GB
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - laborchart

  ct-chrome:
    container_name: ComputrabajoDriver
    hostname: ctdriver
    restart: always
    storage_opt:
      size: 1GB
    image: selenium/standalone-chrome:latest
    ports:
      - 4444:4444
    privileged: true
    shm_size: 2g
    networks:
      - laborchart

  ee-chrome:
    container_name: ElempleoDriver
    hostname: eedriver
    restart: always
    storage_opt:
      size: 1GB
    image: selenium/standalone-chrome:latest
    ports:
      - 4445:4444
    privileged: true
    shm_size: 2g
    networks:
      - laborchart

  dagster:
    container_name: Dagster
    restart: always
    storage_opt:
      size: 1GB
    volumes:
      - ./volumes/dagster-data:/usr/src/app/Dagster
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    networks:
      - laborchart
    depends_on:
      - ee-chrome
      - ct-chrome

volumes:
  elastic-data:

  dagster-data:

networks:
  laborchart:
    name: laborchart
    driver: bridge
